#!/bin/bash -l
#$ -cwd
#$ -S /bin/bash
#$ -V
#$ -q all.q
#$ -l h_vmem=20G
#$ -l s_rt=30:00:00
#$ -pe smp 1
#$ -m a
#$ -M pzhou@caas.cn
#$ -j y
#$ -o job.out
#$ -N zm.cg20a.2

source activate nf
cd $rn/nf/zm.cg20a.2
nextflow run $nf/rnaseq -params-file $proj/genome/nf/genomes.yml -profile conda,caas -resume

